[tool.black]
line-length = 79
target-version = ["py310"]

[tool.isort]
profile = "black"
py_version = 310
length_sort= true

[tool.mypy]
strict = true
pretty = true
ignore_missing_imports = true

[tool.pylint.main]
load-plugins = [
    "pylint.extensions.docparams",
    "pylint.extensions.docstyle",
    "pylint.extensions.code_style",
    "pylint.extensions.mccabe"
]

[tool.pylint.design]
max-complexity = 4

[tool.pylint.format]
max-line-length = "79"

[tool.pylint.parameter_documentation]
accept-no-param-doc = false
accept-no-raise-doc = false
accept-no-return-doc = false
accept-no-yields-doc = false
default-docstring-type = "default"
